<div id="content">
    <div id="content2">

        <table id="table">
            <tr>
                <td class="sweb"><a href="#"></a><img src="/skins/defaultback/images/sweb.png"></td>
                <td class="photos"><a href="#"></a><img src="/skins/defaultback/images/photos.png"></td>
                <td class="topc"><a href="#"></a><img src="/skins/defaultback/images/topc.png"></td>
                <td class="book"><a href="#"></a><img src="/skins/defaultback/images/book.png"></td>
                <td class="scloud"><a href="#"></a><img src="/skins/defaultback/images/scloud.png"></td>
                <td class="rstat"><a href="#"></a><img src="/skins/defaultback/images/rstats.png"></td>
            </tr>
            <tr>
                <td class="tasks"><a href="#"></a><img src="/skins/defaultback/images/tasks.png"></td>
                <td class="calendar"><a href="#"></a><img src="/skins/defaultback/images/calendar.png"></td>
                <td class="acomment"><a href="#"></a><img src="/skins/defaultback/images/acomments.png"></td>
                <td class="qsearch"><a href="#"></a><img src="/skins/defaultback/images/qsearch.png"></td>
                <td class="objectives"><a href="#"></a><img src="/skins/defaultback/images/objctives.png"></td>
                <td  class="suggest"><a href="#"></a><img src="/skins/defaultback/images/suggestion.png"></td>
            </tr>
        </table>

        <!--div class="right-block">
        </div-->
    </div>
</div>