<div id="main-menu">
    <ul>
        <li class="dash"><a href="#" title=""><img src ="/skins/defaultback/images/dash.png"></a></li>
        <li class="menu"><a href="#" title=""><img src ="/skins/defaultback/images/menu.png"></a></li>
        <li class="content"><a href="#" title=""><img src ="/skins/defaultback/images/content.png"></a></li>
        <li class="user"><a href="#" title=""><img src ="/skins/defaultback/images/users.png"></a></li>
        <li class="set"><a href="#" title=""><img src ="/skins/defaultback/images/settings.png"></a></li>
    </ul>
</div>